wip

diff --git a/tools/mkvirtdisk b/tools/mkvirtdisk
--- a/tools/mkvirtdisk
+++ b/tools/mkvirtdisk
@@ -11,7 +11,7 @@
 set -e
 
 function cleanup {
-    rm -f $BUILD_DIR/fat.img
+    rm -f $BUILD_DIR/ext4.img
 }
 
 trap cleanup EXIT
@@ -22,9 +22,9 @@ if [ $# -ne 4 ]; then
     exit 1
 fi
 
-if ! command -v mkfs.fat &> /dev/null
+if ! command -v mkfs.ext4 &> /dev/null
 then
-    echo "mkfs.fat could not be found, please install dosfstools"
+    echo "mkfs.ext4 could not be found, please install dosfstools"
     exit 1
 fi
 
@@ -47,7 +47,7 @@ if [ $(( LSIZE & (LSIZE - 1) )) -ne 0 ] || [ $LSIZE -lt $FDISK_LSIZE ]; then
 fi
 
 if [ $((MEMSIZE)) -lt 114688 ]; then
-    echo "MEMSIZE must be greater than 114688(112 * 1024), sizes smaller than that break either fdisk or mkfs.fat"
+    echo "MEMSIZE must be greater than 114688(112 * 1024), sizes smaller than that break either fdisk or mkfs.ext4"
     exit 1
 fi
 
@@ -123,12 +123,12 @@ else
 fi
 
 # Create the FAT filesystem
-rm -f $BUILD_DIR/fat.img
-mkfs.fat -C $BUILD_DIR/fat.img $(( (FS_COUNT * FDISK_LSIZE) / 1024 )) -F 12 -S $LSIZE
+rm -f $BUILD_DIR/ext4.img
+mkfs.ext4 -C $BUILD_DIR/ext4.img $(( (FS_COUNT * FDISK_LSIZE) / 1024 )) -F 12 -S $LSIZE
 
 # Copy the FAT filesystem to the virtual disk
 for i in $(seq 0 $(( NUM_PARTITIONS - 1 )))
 do
     echo "Copying FAT filesystem to partition $i, seek=$((POFFSET + i * FS_COUNT)), count=$FS_COUNT, bs=$FDISK_LSIZE"
-    dd if=$BUILD_DIR/fat.img of=$DISK_IMAGE bs=$FDISK_LSIZE seek="$((POFFSET + i * FS_COUNT))" count=$FS_COUNT 2> /dev/null
+    dd if=$BUILD_DIR/ext4.img of=$DISK_IMAGE bs=$FDISK_LSIZE seek="$((POFFSET + i * FS_COUNT))" count=$FS_COUNT 2> /dev/null
 done
